#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### For remove operations:
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-web" >/dev/null; then
    yunohost service remove "$app-web"
fi
if ynh_hide_warnings yunohost service status "$app-worker" >/dev/null; then
    yunohost service remove "$app-worker"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_nodejs_remove

# Remove other various files specific to the app... such as:
ynh_safe_rm "/etc/cron.d/$app"

redis_db=$(basename $(grep -Po "location=redis://.*" $install_dir/pretix.cfg))
ynh_redis_remove_db $redis_db
redis_db_backend=$(basename $(grep -Po "backend=redis://.*" $install_dir/pretix.cfg))
ynh_redis_remove_db $redis_db_backend
redis_db_broker=$(basename $(grep -Po "broker=redis://.*" $install_dir/pretix.cfg)) 
ynh_redis_remove_db $redis_db_broker

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
